##############################
# Variables you need to change
##############################

samples: "config/test_coords.csv"            # name of the sample metadata CSV 

##############################
# Variables you *might* need to change
##############################

## QC options ##
nClusters: 3
GoogleAPIKey:
min_depth: 2
