##############################
# Variables you need to change
##############################

samples: "/usr/scratch2/userdata2/tmugoya/THESIS/Arabidopsis_Test/config/SraRunTable.csv" # path to the sample metadata CSV

