##############################
# Variables you need to change
##############################

samples: "config/samples.csv"  # name of the sample metadata CSV 
final_prefix: "" # prefix for final output files

##############################
# Variables you *might* need to change
##############################

## Filtering options ##
